spring.application.name=immo
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=@spring.datasource.url@
spring.datasource.username=@spring.datasource.username@
spring.datasource.password=@spring.datasource.password@
server.port=@server.port@
spring.datasource.pool-size=1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.mysql.console.enabled=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.mvc.hiddenmethod.filter.enabled=true